# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0002_auto_20190815_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
